import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";
import { useSession, signIn, signOut } from "next-auth/react"

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.getAll"]);
  const { data: session } = useSession()
  return (
    <>
      <Head>
        <title>Workout Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="content-center">
          <Link href={"/about"}>
            to about
          </Link>
          {
            session?.user &&
            <>
              Signed in as {session.user.email} <br />
              <button onClick={() => signOut()}>Sign out</button>
            </>
          }
          {
            !session?.user &&
            <>
              Not signed in <br />
              <button onClick={() => signIn()}>Sign in</button>
            </>
          }
        </div>
      </main>
    </>
  );
};

export default Home;