import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.getAll"]);

  return (
    <>
      <Head>
        <title>Workout Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="content-center">
          <Link href={"/about"}>
            to about
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;